# regex pairs to clean the text before speaking
- - ([^.])\.$
  - \1
- - '&amp;'
  - '&'
- - '&lt;'
  - <
- - '&gt;'
  - '>'
- - '&quot;'
  - '"'
- - '&#x27;'
  - ''''
- - '&copy;'
  - '©'
- - '&reg;'
  - '®'
- - '&nbsp;'
  - ' '
- - '"'
  - ''
- - ' biases '
  - ' bias''s '
- - ex\.
  - for example
- - e\.g\.
  - for example
- - ' ESG '
  - ' E.S.G. '
- - ' FY '
  - ' F.Y. '
- - ([0-9]+)-([0-9]+)
  - \1 to \2
- - '[\U0001F600-\U0001F64F\U0001F300-\U0001F5FF\U0001F680-\U0001F6FF\U0001F700-\U0001F77F\U0001F780-\U0001F7FF\U0001F800-\U0001F8FF\U0001F900-\U0001F9FF\U0001FA00-\U0001FA6F\U0001FA70-\U0001FAFF\U00002702-\U000027B0\U000024C2-\U0001F251]+'
  - ''
- - '\*\*\*'
  - '*'
- - '\*\*'
  - '*'
